version: '3.9'

services:
  app:
    build:
      context: ./backend
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    working_dir: /frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./backend/proxy
    restart: always
    depends_on:
      - app
    ports:
      - 8001:8000
    volumes:
      - static-data:/vol/static


volumes:
  postgres-data:
  static-data:
