# Generated by Django 4.1 on 2023-05-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_image_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="description", field=models.TextField(null=True),
        ),
    ]
